stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
   
    outs:
      - data/raw/raw_data.csv

      
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
    outs:
      - data/processed/test.csv
      - data/processed/train.csv

      

  train:
    cmd: python src/train_pipeline.py
    deps:
      - src/train_pipeline.py
      - src/model.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/loan_approval_model.pkl
    # logs:
    #   - logs/train_pipeline.log
    #   - logs/model_buiding.log
    #   - logs/data_ingestion.log
    #   - logs/data_preprocessing.log
